version: "3.8"
services:
  wechatter:
    image: crpi-njrnyyg1qc99zqup.cn-zhangjiakou.personal.cr.aliyuncs.com/jerryestt/docker:preview
#    image: wechatter
    container_name: wechatter
    ports:
      - "4000:4000"
    volumes:
      - ./config_cps.yaml:/wechatter/config.yaml
    environment:
      - WECHATTER_LOG_LEVEL=INFO
