name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: cassius0924
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
              
    - name: Build and push Docker image
      uses: docker/build-push-action@v5.2.0
      with:
        context: .
        push: true
        tags: cassius0924/wechatter:latest
